name    'inkblot/android_ec2_vpn'
version '1.0.1'
source  'git://github.com/inkblot/puppet-android-ec2-vpn'
author  'inkblot'
license 'Apache 2.0'
summary 'L2TP/IPSec PSK VPN server for single Android user'
description 'A Puppet module which sets up a VPN server on an EC2 instance using the xl2tpd L2TP server, the racoon IPSec IKE server'
project_page 'https://github.com/inkblot/puppet-android-ec2-vpn'

dependency 'inkblot/shorewall', '>= 3.0.0'
